#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

PLUGINS_DIR="plugins"
OUTPUT="docs/PLUGIN_AUDIT.md"

CANONICAL_TRACKERS=(
    rutracker kinozal nnmclub iptorrents
    rutor nyaa piratebay eztv solidtorrents yts torrentgalaxy limetorrents
)

INFRASTRUCTURE=(
    helpers nova2 novaprinter socks download_proxy env_loader theme_injector
)

is_canonical() {
    local name="$1"
    for c in "${CANONICAL_TRACKERS[@]}"; do
        [[ "$c" == "$name" ]] && return 0
    done
    for c in "${INFRASTRUCTURE[@]}"; do
        [[ "$c" == "$name" ]] && return 0
    done
    return 1
}

has_test() {
    local name="$1"
    grep -rl "$name" tests/ 2>/dev/null | grep -q .
}

cat > "$OUTPUT" << 'HEADER'
# Plugin Audit Matrix

Generated by `scripts/audit-plugins.sh`.

| Plugin | Last Modified | py_compile | Has Test? | Category | Action |
|--------|--------------|------------|-----------|----------|--------|
HEADER

for f in "$PLUGINS_DIR"/*.py; do
    name="$(basename "$f" .py)"
    mod=$(stat -c '%Y' "$f")
    date=$(date -d "@$mod" '+%Y-%m-%d')

    compile_status="PASS"
    python3 -m py_compile "$f" 2>/dev/null || compile_status="FAIL"

    test_status="no"
    has_test "$name" && test_status="yes"

    if is_canonical "$name"; then
        category="canonical"
        action="adopt"
    else
        category="community"
        action="community"
    fi

    echo "| $name | $date | $compile_status | $test_status | $category | $action |" >> "$OUTPUT"
done

echo "" >> "$OUTPUT"
echo "## Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"

total=$(ls "$PLUGINS_DIR"/*.py | wc -l)
pass=$(for f in "$PLUGINS_DIR"/*.py; do python3 -m py_compile "$f" 2>/dev/null && echo ok; done | wc -l)
fail=$((total - pass))
tested=$(for f in "$PLUGINS_DIR"/*.py; do name=$(basename "$f" .py); grep -rl "$name" tests/ 2>/dev/null | grep -q . && echo ok; done | wc -l)
canonical_count=${#CANONICAL_TRACKERS[@]}
community_count=$((total - canonical_count - ${#INFRASTRUCTURE[@]}))

echo "- **Total plugins**: $total" >> "$OUTPUT"
echo "- **py_compile pass**: $pass" >> "$OUTPUT"
echo "- **py_compile fail**: $fail" >> "$OUTPUT"
echo "- **Has tests**: $tested" >> "$OUTPUT"
echo "- **Canonical trackers**: $canonical_count" >> "$OUTPUT"
echo "- **Infrastructure**: ${#INFRASTRUCTURE[@]}" >> "$OUTPUT"
echo "- **Community**: $community_count" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "### Canonical Tracker Plugins (managed)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
for c in "${CANONICAL_TRACKERS[@]}"; do
    echo "- \`$c\`" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"
echo "### Infrastructure (non-tracker)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
for c in "${INFRASTRUCTURE[@]}"; do
    echo "- \`$c\`" >> "$OUTPUT"
done

echo "Audit written to $OUTPUT"
