#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

PLUGINS_DIR="plugins"
OUTPUT="docs/PLUGIN_AUDIT.md"

CANONICAL_TRACKERS=(
    rutracker kinozal nnmclub iptorrents
    rutor nyaa piratebay eztv solidtorrents yts torrentgalaxy limetorrents
)

INFRASTRUCTURE=(
    helpers nova2 novaprinter socks download_proxy env_loader theme_injector
)

is_canonical() {
    local name="$1"
    for c in "${CANONICAL_TRACKERS[@]}"; do
        [[ "$c" == "$name" ]] && return 0
    done
    for c in "${INFRASTRUCTURE[@]}"; do
        [[ "$c" == "$name" ]] && return 0
    done
    return 1
}

has_test() {
    local name="$1"
    grep -rl "$name" tests/ 2>/dev/null | grep -q .
}

cat > "$OUTPUT" << 'HEADER'
# Plugin Audit Matrix

Generated by `scripts/audit-plugins.sh`.

| Plugin | Last Modified | py_compile | Has Test? | Category | Action |
|--------|--------------|------------|-----------|----------|--------|
HEADER

audit_file() {
    local f="$1"
    local category="$2"
    local action="$3"
    local name mod date
    name="$(basename "$f" .py)"
    mod=$(stat -c '%Y' "$f")
    date=$(date -d "@$mod" '+%Y-%m-%d')

    local compile_status="PASS"
    python3 -m py_compile "$f" 2>/dev/null || compile_status="FAIL"

    local test_status="no"
    has_test "$name" && test_status="yes"

    echo "| $name | $date | $compile_status | $test_status | $category | $action |" >> "$OUTPUT"
}

for f in "$PLUGINS_DIR"/*.py; do
    name="$(basename "$f" .py)"
    if is_canonical "$name"; then
        audit_file "$f" "canonical" "adopt"
    else
        audit_file "$f" "infrastructure" "keep"
    fi
done

if [[ -d "$PLUGINS_DIR/community" ]]; then
    for f in "$PLUGINS_DIR/community"/*.py; do
        [[ -f "$f" ]] && audit_file "$f" "community" "community"
    done
fi

echo "" >> "$OUTPUT"
echo "## Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"

total=$(ls "$PLUGINS_DIR"/*.py | wc -l)
community_total=0
if [[ -d "$PLUGINS_DIR/community" ]]; then
    community_total=$(ls "$PLUGINS_DIR/community"/*.py 2>/dev/null | wc -l)
fi
grand_total=$((total + community_total))
pass=0
for f in "$PLUGINS_DIR"/*.py "$PLUGINS_DIR/community"/*.py; do
    [[ -f "$f" ]] || continue
    python3 -m py_compile "$f" 2>/dev/null && ((pass++)) || true
done
fail=$((grand_total - pass))
tested=0
for f in "$PLUGINS_DIR"/*.py "$PLUGINS_DIR/community"/*.py; do
    [[ -f "$f" ]] || continue
    name=$(basename "$f" .py)
    grep -rl "$name" tests/ 2>/dev/null | grep -q . && ((tested++)) || true
done
canonical_count=${#CANONICAL_TRACKERS[@]}

echo "- **Total files**: $grand_total" >> "$OUTPUT"
echo "- **py_compile pass**: $pass" >> "$OUTPUT"
echo "- **py_compile fail**: $fail" >> "$OUTPUT"
echo "- **Has tests**: $tested" >> "$OUTPUT"
echo "- **Canonical trackers**: $canonical_count" >> "$OUTPUT"
echo "- **Infrastructure**: ${#INFRASTRUCTURE[@]}" >> "$OUTPUT"
echo "- **Community**: $community_total" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "### Canonical Tracker Plugins (managed)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
for c in "${CANONICAL_TRACKERS[@]}"; do
    echo "- \`$c\`" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"
echo "### Infrastructure (non-tracker)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
for c in "${INFRASTRUCTURE[@]}"; do
    echo "- \`$c\`" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"
echo "### Community Plugins" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "See \`plugins/community/\` directory. Install individually per \`plugins/community/README.md\`." >> "$OUTPUT"

echo "Audit written to $OUTPUT"
